import { Property, Agent } from './types';

export const BUSINESS_INFO = {
  name: 'ALPHADAVIS REAL ESTATE LIMITED',
  address: 'M33 Mabel plaza, Opposite Makamachi Auto Care, #47 Presidential Road Enugu.',
  phone: '08069443282',
  mainPhone: '2349071111211',
  email: 'info@alphadavisrealestate.com',
  logo: 'https://i.postimg.cc/MHqCmSWF/Alphadavis(1).png',
  description: 'Where dreams and affordable housing meet reality. We are dedicated to transforming the Real Estate industry by providing innovative and sustainable housing solutions for our global clientele.',
  vision: 'To be the most trusted and global real estate firm, setting the standard for integrity and excellence in property development, and exceptional clients solutions.',
  mission: 'Dedicated to empowering clients with endless possibilities and sustainable real estate solutions by building long-term relationships based on integrity, professionalism, and satisfaction'
};

export const SOCIAL_LINKS = {
  facebook: 'https://www.facebook.com/profile.php?id=61588923493600',
  instagram: 'https://www.instagram.com/alphadavisofficial',
  whatsapp: 'https://wa.me/2348069443282',
};

export const SEED_PROPERTIES = [
  {
    title: 'ALPHAMEGA CITY',
    slug: 'alphamega-city',
    location: 'EKWEGBE, ENUGU STATE',
    price: 1700000,
    priceLabel: '₦1,700,000',
    bedrooms: 0,
    bathrooms: 0,
    toilets: 0,
    parkingSpaces: 0,
    floorAreaSqm: 500,
    coverImageUrl: 'https://i.postimg.cc/SRbVQg7V/Whats-App-Image-2026-05-04-at-2-58-28-PM(1).jpg',
    status: 'Pre-Sale Price',
    propertyType: 'Land',
    listingType: 'sale',
    state: 'Enugu',
    city: 'Ekwegbe',
    neighborhood: 'Ekwegbe',
    address: 'Ekwegbe - Enugu State, 1 min from Enugu-Nsukka Dual Tarred Road',
    description: 'ALPHAMEGA CITY:\nLocation: Ekwegbe - Enugu State.\n\nLANDMARKS:\n- 1 min from Enugu - Nsukka Dual Tarred Road.\n- 5 mins from Maduka University Ekwegbe\n- 4 mins from Nkwo Ekwegbe Market.\n- 1 min from human habitation.\n- 3 mins from Mopol 36 base\n\nTITLE DOCUMENTS (FREE):\n- Receipt\n- Deed of assignment\n- Power of Attorney\n- Instant allocation\n- Registered survey plan\n\nSIZE: 500 SQM (PLOT SIZE)\n\nActual price: ₦3,500,000',
    amenities: ['Good Road', 'Fence/Gated', 'Recreational Arena', 'Shopping Mall', 'School', 'Standard Clinic', '24/7 Power', 'Water', '24/7 Security'],
    isFeatured: true,
    isDiasporaPick: false,
    isNewListing: true,
    isPublished: true,
    negotiable: false,
    galleryImages: [],
    videoUrl: '',
  },
  {
    title: 'PUREHAVEN ESTATE',
    slug: 'purehaven-estate',
    location: 'OWO, ENUGU STATE',
    price: 2000000,
    priceLabel: '₦2,000,000',
    bedrooms: 0,
    bathrooms: 0,
    toilets: 0,
    parkingSpaces: 0,
    floorAreaSqm: 500,
    coverImageUrl: 'https://i.postimg.cc/9MgpHxRD/Whats-App-Image-2026-05-04-at-2-58-27-PM(1).jpg',
    status: 'Pre-Sale Offer',
    propertyType: 'Land',
    listingType: 'sale',
    state: 'Enugu',
    city: 'Owo',
    neighborhood: 'Owo',
    address: 'Along the newly tarred Owo-Abuja Express Road, Enugu State',
    description: 'PUREHAVEN ESTATE:\nThis estate is located in a fast developing area of Owo, Enugu State. Strategically located along the newly tarred Owo-Abuja Express Road.\n\nLANDMARKS:\n- Along the newly tarred Owo-Abuja Road.\n- Opposite World Bank Assisted Project in livestock and Hospitality management\n- Behind PWan Estate and Evolve City Estate\n- 2 mins from Africa Medical City and Osisatech Polytechnic.\n- 4 mins from Capstone University and Senior Model Secondary School\n- 5 mins from St. Mary Parish/Catholic Diocese of Enugu and Owo Smart School\n- 7 mins from Owo International Market.\n\nTITLE DOCUMENTS (FREE):\n- Deed of assignment\n- Power of Attorney\n- Instant allocation\n- Registered survey plan\n- Receipt\n\nSIZE: 500 SQM (PLOT SIZE)',
    amenities: ['Good Road', 'Fence/Gated', 'Recreational Arena', 'Shopping Mall', 'School', 'Electricity/Water'],
    isFeatured: true,
    isDiasporaPick: false,
    isNewListing: true,
    isPublished: true,
    negotiable: false,
    galleryImages: [],
    videoUrl: '',
  },
  {
    title: 'ALPHADAVIS ESTATE',
    slug: 'alphadavis-estate',
    location: 'Ogbeke Nike, Enugu',
    price: 3000000,
    priceLabel: '₦3,000,000',
    bedrooms: 0,
    bathrooms: 0,
    toilets: 0,
    parkingSpaces: 0,
    floorAreaSqm: 500,
    coverImageUrl: 'https://i.ibb.co/zW90T79M/IMG-20260504-WA0005.jpg',
    status: 'Selling Now',
    propertyType: 'Land',
    listingType: 'sale',
    state: 'Enugu',
    city: 'Enugu',
    neighborhood: 'Ogbeke Nike',
    address: 'Ogbeke Nike-Enugu Behind Seaman Estate, Close Final Point Hotel',
    description: 'ALPHADAVIS ESTATE:\nRC Number: RC 9339040.\nLocation: Ogbeke Nike-Enugu Behind Seaman Estate, Close Final Point Hotel.\nProximity: 5 mins from Nike Lake Hotel, Enugu State.\n\nIncludes Deed of assignment, Power of Attorney, Instant allocation, Registered survey plan, and Receipt.',
    amenities: ['Good Road', 'Fence/Gated', 'Recreational Arena', 'Shopping Mall', 'School', 'Electricity/Water'],
    isFeatured: true,
    isDiasporaPick: false,
    isNewListing: false,
    isPublished: true,
    negotiable: true,
    galleryImages: [],
    videoUrl: '',
  }
];

export const AGENTS: Agent[] = [
  {
    id: '1',
    name: 'Rita Uduebholo',
    role: 'Principal Agent',
    image: 'https://i.postimg.cc/FR5592LY/2148190690.jpg',
    phone: '0811 370 2466',
    email: 'ritauduebholo@gmail.com'
  },
  {
    id: '2',
    name: 'Chidi Okafor',
    role: 'Senior Consultant',
    image: 'https://i.postimg.cc/NMqqgWHL/2151064880.jpg',
    phone: '0800 000 0000',
    email: 'chidi@alphadavis.com'
  }
];